import { getCurrentThemeColor } from '../utils';
import { anomalyGlyph, anomalyName, audioLabel, currentShift, lampLabel } from './engine';
import { ROOM_NAMES } from './content';
import type { GameState, RoomId } from './types';

const esc = '\x1b[';
const ansi = (code: string, text: string) => `${esc}${code}m${text}${esc}0m`;
const bar = (value: number, max: number, full = '#', empty = '-') => full.repeat(Math.max(0, Math.min(max, value))) + empty.repeat(Math.max(0, max - value));
const fit = (text: string, width: number) => text.length > width ? `${text.slice(0, Math.max(0, width - 1))}…` : text.padEnd(width);
const line = (x: number, y: number, text: string) => `${esc}${y};${x}H${text}`;

function roomLine(state: GameState, id: RoomId): string {
  const room = state.rooms[id]; const anomaly = room.anomalyId ? state.anomalies[room.anomalyId] : undefined; const status = room.breached ? '×' : anomaly && anomaly.pressure >= 4 ? '!' : '◆'; const anomalyText = anomaly ? `${anomalyGlyph(anomaly.id)}${anomaly.pressure}` : '--'; return `${id} ${status} ${anomalyText} ${lampLabel(room.lamp).slice(0, 1)} ${room.audio.slice(0, 1).toUpperCase()} ${room.door === 'sealed' ? '#' : '.'}`;
}

export function renderFrame(state: GameState, cols: number, rows: number, themeColor = getCurrentThemeColor(), glitchFrame = 0): string {
  if (cols < 80 || rows < 28) return `${esc}2J${esc}H${line(Math.max(1, Math.floor((cols - 18) / 2)), Math.max(1, Math.floor(rows / 2) - 1), ansi('1;91', 'TERMINAL TOO SMALL'))}${line(1, Math.max(1, Math.floor(rows / 2) + 1), `Need 80x28  Have ${cols}x${rows}`)}`;
  let out = `${esc}2J${esc}H`; const title = glitchFrame % 60 > 55 ? 'C0NTAINMENT PR0T0C0L' : 'CONTAINMENT PROTOCOL'; out += line(Math.floor((cols - title.length) / 2), 1, `${themeColor}${title}${esc}0m`);
  if (state.phase === 'start') { out += line(25, 5, ansi('1;96', 'HALCYON ANNEX / NIGHT CONTROL')); out += line(27, 8, 'T  TUTORIAL'); out += line(27, 9, 'C  CAMPAIGN'); out += line(27, 10, 'N  NIGHT WATCH'); out += line(21, 14, 'Learn the rule. Hold the room.'); return out; }
  if (state.phase === 'briefing') { const shift = currentShift(state); out += line(8, 5, ansi('1;93', `SHIFT ${state.shiftIndex + 1}: ${shift.title}`)); out += line(8, 7, fit(shift.brief, 64)); out += line(8, 10, 'ACTIVE ANOMALIES:'); let y = 11; for (const anomaly of Object.values(state.anomalies)) { out += line(10, y++, `${anomalyGlyph(anomaly.id)} ${anomalyName(anomaly.id)} — ${state.rooms[anomaly.roomId].id}`); } out += line(8, 17, 'ENTER  begin observation    R  rules / dossier'); return out; }
  const integrity = bar(state.integrity, 6, '◆', '·'); const battery = bar(state.battery, 6, '▰', '·'); out += line(3, 3, `INTEGRITY ${integrity}  POWER ${state.powerCapacity}  BATTERY ${battery}  CYCLES ${String(state.cyclesRemaining).padStart(2, '0')}  SHIFT ${state.shiftIndex + 1}`);
  out += line(3, 4, ansi('1;93', fit(state.notice, cols - 6)));
  out += line(3, 6, '┌─ STATION MAP ─────────────────────────┐'); out += line(3, 7, `│       [A ${roomLine(state, 'A')}]──[B ${roomLine(state, 'B')}]       │`); out += line(3, 8, '│            │          │              │'); out += line(3, 9, `│ [G]──────[H ${state.technicianRoom === 'H' ? '@' : '·'}]──────[C ${roomLine(state, 'C')}]       │`); out += line(3, 10, '│                       │              │'); out += line(3, 11, `│                     [D ${roomLine(state, 'D')}]       │`); out += line(3, 12, '└──────────────────────────────────────┘');
  const room = state.rooms[state.selectedRoom]; const anomaly = room.anomalyId ? state.anomalies[room.anomalyId] : undefined; out += line(45, 6, `┌─ CHAMBER ${state.selectedRoom} / ${ROOM_NAMES[state.selectedRoom]} ─────────────┐`); out += line(45, 7, `│ PRESSURE ${anomaly ? `[${bar(anomaly.pressure, 6)}] ${anomaly.pressure}/6` : 'EMPTY'}             │`); out += line(45, 8, `│ ANOMALY  ${fit(anomaly ? `${anomalyGlyph(anomaly.id)} ${anomalyName(anomaly.id)}` : 'NONE', 32)} │`); out += line(45, 9, `│ LAMP ${lampLabel(room.lamp).padEnd(8)} AUDIO ${audioLabel(room.audio).padEnd(7)} │`); out += line(45, 10, `│ DOOR ${room.door.toUpperCase().padEnd(8)} TECH ${state.technicianRoom === state.selectedRoom ? 'INSIDE' : 'REMOTE'}  │`); out += line(45, 11, `│ EVIDENCE ${anomaly ? `${anomaly.knownEvidence.length}/2 ${anomaly.confirmed ? '✓ CONFIRMED' : ''}` : '--'}                 │`); out += line(45, 12, '└─────────────────────────────────────────┘');
  out += line(3, 14, '┌─ ROOM CONFIGURATION ───────────────────┐'); out += line(3, 15, `│ A ${roomLine(state, 'A')}   B ${roomLine(state, 'B')}   C ${roomLine(state, 'C')}   D ${roomLine(state, 'D')} │`); out += line(3, 16, `│ DEMAND PREVIEW  ${state.lastCycle ? `${state.lastCycle.demand}/${state.lastCycle.capacity}` : '—'}  [1-3 lamp] [S/H/W/T sound] │`); out += line(3, 17, '└────────────────────────────────────────┘');
  out += line(45, 14, '┌─ INCIDENT LOG ─────────────────────────┐'); const logs = state.incidents.slice(-5); for (let i = 0; i < 5; i++) out += line(45, 15 + i, `│ ${fit(logs[i] ? `C${String(logs[i].cycle).padStart(2, '0')} ${logs[i].text}` : '', 39)}│`); out += line(45, 20, '└─────────────────────────────────────────┘');
  out += line(3, 23, '[←→] room  [1-3] lamp  [S/H/W/T] audio  [D] door  [M] move  [P] probe'); out += line(3, 24, '[Enter] commit cycle  [R] rules  [L] log  [H] help  [Esc] pause  [Q] quit');
  if (state.phase === 'cycleReport') { out += line(22, 26, ansi('1;91', 'CYCLE RESOLVED — ENTER to continue')); } else if (state.phase === 'shiftReport') { out += line(17, 26, ansi('1;92', 'SHIFT COMPLETE — choose an upgrade with 1/2/3')); const offers = state.upgradeOffers.length ? state.upgradeOffers : []; offers.forEach((offer, i) => { out += line(8, 27 + i, `${i + 1}. ${offer.name}: ${offer.text}`); }); } else if (state.phase === 'gameOver') out += line(20, 26, ansi('1;91', 'CONTAINMENT FAILED — R restart shift / Q quit')); else if (state.phase === 'ending') out += line(23, 26, ansi('1;92', 'HANDOFF ACCEPTED — N next game / Q quit')); return out;
}
