import { caseById, evidenceById, judgeById, precedentById, ADVOCATES } from './content';
import type { GameState, FaceSymbol, HearingPreview, Rank } from './types';

const RESET = '\x1b[0m'; const DIM = '\x1b[2m'; const BOLD = '\x1b[1m'; const RED = '\x1b[91m'; const GREEN = '\x1b[92m'; const YELLOW = '\x1b[93m'; const CYAN = '\x1b[96m'; const MAGENTA = '\x1b[95m';
let frameState: GameState | undefined;
const faceLetter: Record<FaceSymbol, string> = { fact: 'F', witness: 'W', law: 'L', rhetoric: 'R', objection: 'O', gaffe: 'X' };
function stripAnsi(value: string): string { return value.replace(/\x1b\[[0-9;]*m/g, ''); }
function wrap(text: string, width: number): string[] { const result: string[] = []; let line = ''; for (const word of text.split(/\s+/)) { if (line && line.length + word.length + 1 > width) { result.push(line); line = word; } else line = line ? `${line} ${word}` : word; } if (line) result.push(line); return result.length ? result : ['']; }
function bar(value: number, max: number, width: number, color: string): string { const filled = Math.max(0, Math.min(width, Math.round((value / Math.max(1, max)) * width))); return `${color}${'█'.repeat(filled)}${DIM}${'░'.repeat(width - filled)}${RESET} ${value}/${max}`; }
function symbol(symbol: FaceSymbol, rank: Rank | 0): string { return `[${faceLetter[symbol]}${rank || ' '}]`; }
function faceFor(state: GameState, dieId: string): { symbol: FaceSymbol; rank: Rank | 0; rerolls: number; marked: boolean } | undefined { const rolled = state.activeCase?.hearing.rolled.find(item => item.dieId === dieId); const die = state.dice.find(item => item.id === dieId); const face = rolled && die ? die.faces[rolled.faceIndex] : undefined; return rolled && face ? { symbol: face.symbol, rank: face.rank, rerolls: rolled.rerollCount, marked: rolled.marked } : undefined; }
function assignmentText(state: GameState, evidenceId: string, slotIndex: number): string { const assignment = state.activeCase?.hearing.assignments.find(item => item.target.kind === 'evidence' && item.target.evidenceId === evidenceId && item.target.slotIndex === slotIndex); if (!assignment) return '__'; const rolled = faceFor(state, assignment.dieId); return `${assignment.dieId.slice(0, 2).toUpperCase()}:${rolled ? symbol(rolled.symbol, rolled.rank) : '__'}`; }
function put(out: string[], x: number, y: number, text: string): void { out.push(`\x1b[${Math.max(1, y)};${Math.max(1, x)}H${text}`); }
function center(out: string[], cols: number, y: number, text: string, color: string): void { put(out, Math.max(1, Math.floor((cols - stripAnsi(text).length) / 2) + 1), y, `${color}${text}${RESET}`); }
function box(out: string[], x: number, y: number, width: number, height: number, color: string): void { put(out, x, y, `${color}┌${'─'.repeat(width - 2)}┐${RESET}`); for (let row = 1; row < height - 1; row++) put(out, x, y + row, `${color}│${RESET}${' '.repeat(width - 2)}${color}│${RESET}`); put(out, x, y + height - 1, `${color}└${'─'.repeat(width - 2)}┘${RESET}`); }
function title(out: string[], cols: number, frame: number, theme: string): void { const text = '§ D I C E   T R I B U N A L §'; const glitch = frame % 60 >= 56; center(out, cols, 1, glitch ? '§ D!CE TR!BUNAL §' : text, glitch ? `${RED}${BOLD}` : `${theme}${BOLD}`); }
function header(out: string[], state: GameState, cols: number, theme: string): void { const line = `CIRCUIT ${state.circuit}  CASE ${Math.min(9, state.caseNumber || state.history.length + 1)}/9   ♥ ${bar(state.standing, state.maxStanding, 8, GREEN)}   $ ${state.fees}   #${state.seed}`; put(out, 3, 3, `${theme}${line}${RESET}`); if (cols > 100) put(out, cols - 26, 3, `${DIM}${theme}ESC: PAUSE${RESET}`); }

export function renderFrame(state: GameState, cols: number, rows: number, theme: string, frame: number, selection = 0, help = false): string {
  frameState = state;
  const out: string[] = ['\x1b[2J\x1b[H'];
  if (cols < 80 || rows < 28) { center(out, cols, Math.max(2, Math.floor(rows / 2) - 1), 'TERMINAL TOO SMALL', `${RED}${BOLD}`); center(out, cols, Math.floor(rows / 2) + 1, `NEED 80x28  HAVE ${cols}x${rows}`, `${DIM}${theme}`); return out.join(''); }
  title(out, cols, frame, theme); header(out, state, cols, theme);
  if (state.phase === 'start') renderStart(out, cols, theme);
  else if (state.phase === 'advocateSelect') renderAdvocates(out, cols, theme, selection);
  else if (state.phase === 'docket') renderDocket(out, cols, theme, selection);
  else if (state.phase === 'briefing') renderBriefing(out, cols, theme);
  else if (state.phase === 'evidenceSelect') renderEvidenceSelect(out, cols, theme, selection);
  else if ((state.phase === 'hearing' || state.phase === 'hearingResult') && cols >= 100) renderHearing(out, cols, theme, selection);
  else if (state.phase === 'hearing' || state.phase === 'hearingResult') renderHearingCompact(out, state, cols, theme, selection);
  else if (state.phase === 'caseResult') renderCaseResult(out, cols, theme);
  else if (state.phase === 'precedentDraft') renderPrecedents(out, cols, theme, selection);
  else if (state.phase === 'chambers') renderChambers(out, cols, theme, selection);
  else if (state.phase === 'circuitReport') renderCircuit(out, cols, theme);
  else renderEnding(out, frameState!, cols, theme);
  if (help) renderHelp(out, cols, rows, theme);
  return out.join('');
}

function footer(out: string[], cols: number, text: string, theme: string): void { center(out, cols, 27, text, `${DIM}${theme}`); }
function renderStart(out: string[], cols: number, theme: string): void { center(out, cols, 8, 'ROLL THE EVIDENCE. RISK THE REROLL. REWRITE PRECEDENT.', `${CYAN}${BOLD}`); center(out, cols, 12, 'A courtroom roguelite for people who object to gravity.', `${DIM}${theme}`); center(out, cols, 17, 'P: PLAY CAMPAIGN    T: TUTORIAL    Q: QUIT', `${YELLOW}${BOLD}`); footer(out, cols, 'The bench is unpredictable. The rules are visible.', theme); }
function renderAdvocates(out: string[], cols: number, theme: string, selection: number): void { box(out, 8, 5, cols - 16, 19, theme); put(out, 11, 6, `${theme}${BOLD}CHOOSE YOUR ADVOCATE${RESET}`); ADVOCATES.forEach((item, i) => { const color = i === selection ? `${YELLOW}${BOLD}` : theme; put(out, 12, 8 + i * 3, `${color}${i + 1}. ${item.name} — ${item.title}${RESET}`); put(out, 17, 9 + i * 3, `${DIM}${theme}${wrap(item.passive, cols - 22)[0]}${RESET}`); }); footer(out, cols, '1-4 SELECT   ENTER CONFIRM   ARROWS MOVE   ESC PAUSE', theme); }
function renderDocket(out: string[], cols: number, theme: string, selection: number): void { const state = frameState; box(out, 7, 5, cols - 14, 19, theme); put(out, 10, 6, `${theme}${BOLD}DOCKET ${stateLabel('SELECT ONE OF THE DISCLOSED CASES')}${RESET}`); if (state) renderDocketBody(out, state, theme, selection); footer(out, cols, '1-2 SELECT DOCKET   ENTER CONFIRM   H: HELP   ESC PAUSE', theme); }
function stateLabel(value: string): string { return `// ${value}`; }

// The state is passed through a small local binding in the specialized renderer below.
function renderDocketBody(out: string[], state: GameState, theme: string, selection: number): void { state.docket.forEach((choice, i) => { const item = caseById(choice.caseId); const judge = judgeById(choice.judgeId); if (!item || !judge) return; const color = i === selection ? `${YELLOW}${BOLD}` : theme; put(out, 11, 9 + i * 6, `${color}${i + 1}. ${item.title}${RESET}`); put(out, 15, 10 + i * 6, `${theme}${item.client} vs ${item.opponent}  ◆${choice.burden}  ▲${choice.pressure.join('/')}  §${judge.name}${RESET}`); put(out, 15, 11 + i * 6, `${DIM}${theme}${wrap(item.premise, 62)[0]}${RESET}`); }); }
function renderBriefing(out: string[], cols: number, theme: string): void { const state = frameState; if (!state?.activeCase) return; const item = caseById(state.activeCase.definitionId); const judge = judgeById(state.activeCase.judgeId); if (!item || !judge) return; box(out, 7, 5, cols - 14, 19, theme); put(out, 10, 6, `${theme}${BOLD}${item.title}${RESET}`); put(out, 10, 8, `${CYAN}${item.client}  v.  ${item.opponent}${RESET}`); wrap(item.premise, cols - 24).slice(0, 2).forEach((line, i) => put(out, 10, 10 + i, `${theme}${line}${RESET}`)); put(out, 10, 14, `${MAGENTA}${BOLD}§ ${judge.name}${RESET}`); put(out, 13, 15, `${theme}1. ${judge.defaultInterpretation.title}: ${judge.defaultInterpretation.text}${RESET}`); put(out, 13, 17, `${theme}2. ${judge.alternateInterpretation.title}: ${judge.alternateInterpretation.text}  [$${judge.alternateInterpretation.fee}]${RESET}`); put(out, 10, 21, `${YELLOW}BURDEN ${item.burden}   PRESSURE ${item.pressure.join(' / ')}   CONTEMPT LIMIT ${item.contemptLimit}${RESET}`); footer(out, cols, '1 DEFAULT   2 FILE MOTION   ENTER ACCEPT DEFAULT   H HELP', theme); }
function renderEvidenceSelect(out: string[], cols: number, theme: string, selection: number): void { const state = frameState; if (!state?.activeCase) return; box(out, 7, 5, cols - 14, 19, theme); put(out, 10, 6, `${theme}${BOLD}SELECT FOUR EXHIBITS${RESET}`); state.evidencePortfolio.forEach((id, i) => { const evidence = evidenceById(id); if (!evidence) return; const selected = state.activeCase!.selectedEvidenceIds.includes(id); const color = i === selection ? `${YELLOW}${BOLD}` : selected ? GREEN : theme; put(out, 10, 8 + i * 2, `${color}${selected ? '+' : ' '} ${i + 1}. ${evidence.name}  ◆${evidence.baseArgument}  [${evidence.slots.map(slot => `${slot.symbol.toUpperCase()}${slot.minRank}`).join(' ')}]${RESET}`); }); put(out, Math.floor(cols / 2) + 4, 8, `${theme}CASE TAGS: ${caseById(state.activeCase.definitionId)?.tags.join(', ').toUpperCase()}${RESET}`); put(out, Math.floor(cols / 2) + 4, 10, `${theme}SELECTED: ${state.activeCase.selectedEvidenceIds.length}/4${RESET}`); footer(out, cols, '1-8 TOGGLE   ENTER CONFIRM CASE FILE   ARROWS MOVE', theme); }

function renderHearing(out: string[], cols: number, theme: string, selection: number): void { const state = frameState; if (!state?.activeCase) return; const active = state.activeCase; const item = caseById(active.definitionId); const judge = judgeById(active.judgeId); box(out, 2, 5, 28, 19, theme); box(out, 31, 5, 43, 19, theme); box(out, 76, 5, Math.min(31, cols - 77), 19, theme); put(out, 4, 6, `${theme}${BOLD}CASE / BENCH${RESET}`); put(out, 4, 8, `${CYAN}${wrap(item?.title ?? '', 24)[0]}${RESET}`); put(out, 4, 10, `${GREEN}◆ ${bar(active.argument, active.burden, 12, GREEN)}${RESET}`); put(out, 4, 11, `${RED}▲ ${bar(active.contempt, active.contemptLimit, 12, RED)}${RESET}`); put(out, 4, 13, `${YELLOW}H${active.hearing.index + 1}/${active.pressure.length}  PRESSURE ${active.pressure[active.hearing.index] ?? 0}${RESET}`); put(out, 4, 15, `${MAGENTA}§ ${judge?.name ?? ''}${RESET}`); wrap(judge?.defaultInterpretation.id === active.interpretationId ? judge.defaultInterpretation.text : judge?.alternateInterpretation.text ?? '', 22).slice(0, 2).forEach((line, i) => put(out, 4, 16 + i, `${DIM}${theme}${line}${RESET}`)); put(out, 33, 6, `${theme}${BOLD}CASE FILE / ASSIGNMENT${RESET}`); active.selectedEvidenceIds.forEach((id, i) => { const evidence = evidenceById(id); if (!evidence) return; const admitted = active.admittedEvidenceIds.includes(id); const slots = evidence.slots.map((_, slot) => assignmentText(state, id, slot)).join(' '); const color = admitted ? DIM : theme; put(out, 33, 8 + i * 3, `${color}${admitted ? '+' : '◇'} ${evidence.name}${RESET}`); put(out, 37, 9 + i * 3, `${color}[${slots}]  ◆${evidence.baseArgument}${admitted ? ' ADMITTED' : ''}${RESET}`); }); put(out, 33, 19, `${theme}CLARIFY [${assignmentFor(state, 'clarify')}]  OBJECT [${assignmentFor(state, 'object')}]${RESET}`); put(out, 78, 6, `${theme}${BOLD}DICE${RESET}`); state.dice.forEach((die, i) => { const result = faceFor(state, die.id); const color = i === selection ? `${YELLOW}${BOLD}` : theme; put(out, 78, 8 + i * 2, `${color}${i + 1}. ${die.name.slice(0, 7).padEnd(7)} ${result ? symbol(result.symbol, result.rank) : '[--]'} ${result?.marked ? 'R' : result?.rerolls ? `x${result.rerolls}` : '#'}${RESET}`); }); put(out, 78, 19, `${YELLOW}REROLLS ${active.hearing.rerollsRemaining}${RESET}`); const preview = state.pendingPreview; if (preview) renderPreview(out, preview, theme, cols); else put(out, 33, 22, `${DIM}${theme}${state.notice.slice(0, Math.max(20, cols - 38))}${RESET}`); footer(out, cols, '1-5 MARK DICE   R REROLL   A AUTO-ASSIGN   U UNASSIGN   ENTER COMMIT   H HELP', theme); }
function renderHearingCompact(out: string[], state: GameState, cols: number, theme: string, selection: number): void {
  const active = state.activeCase!; const item = caseById(active.definitionId); const judge = judgeById(active.judgeId);
  box(out, 2, 5, 25, 19, theme); box(out, 28, 5, cols - 30, 19, theme);
  put(out, 4, 6, `${theme}${BOLD}CASE${RESET}`); put(out, 4, 8, `${CYAN}${wrap(item?.title ?? '', 21)[0]}${RESET}`); put(out, 4, 10, `${GREEN}◆ ${active.argument}/${active.burden}${RESET}`); put(out, 4, 11, `${RED}▲ ${active.contempt}/${active.contemptLimit}${RESET}`); put(out, 4, 13, `${YELLOW}H${active.hearing.index + 1}/${active.pressure.length} P${active.pressure[active.hearing.index] ?? 0}${RESET}`); put(out, 4, 15, `${MAGENTA}§ ${(judge?.name ?? '').slice(0, 18)}${RESET}`); put(out, 4, 17, `${DIM}${theme}${state.notice.slice(0, 19)}${RESET}`);
  put(out, 30, 6, `${theme}${BOLD}DICE / FILE${RESET}`); state.dice.forEach((die, i) => { const result = faceFor(state, die.id); put(out, 30 + i * 9, 8, `${i + 1}:${result ? symbol(result.symbol, result.rank) : '[--]'}`); }); put(out, 30, 10, `${YELLOW}REROLLS ${active.hearing.rerollsRemaining}${RESET}`);
  active.selectedEvidenceIds.forEach((id, i) => { const evidence = evidenceById(id); if (!evidence) return; const admitted = active.admittedEvidenceIds.includes(id); const slots = evidence.slots.map((_, slot) => assignmentText(state, id, slot)).join(' '); put(out, 30, 12 + i * 2, `${admitted ? DIM : theme}${admitted ? '+' : '◇'} ${evidence.name.slice(0, 19)} [${slots}]${RESET}`); });
  put(out, 30, 21, `${theme}C[${assignmentFor(state, 'clarify')}] O[${assignmentFor(state, 'object')}]${RESET}`); if (state.pendingPreview) put(out, 30, 22, `${YELLOW}◆+${state.pendingPreview.argumentDelta} ▲+${state.pendingPreview.contemptDelta} ${state.pendingPreview.outcome.toUpperCase()}${RESET}`);
  void cols; void selection;
  footer(out, cols, '1-5 MARK   R REROLL   A AUTO   U UNASSIGN   ENTER COMMIT', theme);
}
function assignmentFor(state: GameState, kind: 'clarify' | 'object'): string { const assignment = state.activeCase?.hearing.assignments.find(item => item.target.kind === kind); if (!assignment) return '__'; const result = faceFor(state, assignment.dieId); return result ? `${assignment.dieId.slice(0, 2).toUpperCase()}:${symbol(result.symbol, result.rank)}` : '__'; }
function renderPreview(out: string[], preview: HearingPreview, theme: string, cols: number): void { put(out, 33, 21, `${preview.outcome === 'win' ? GREEN : preview.outcome === 'sanction' || preview.outcome === 'timeout' ? RED : YELLOW}${BOLD}COMMIT PREVIEW${RESET}`); put(out, 33, 22, `${theme}◆ +${preview.argumentDelta}  ⊘ BLOCK ${preview.block}  ▲ +${preview.contemptDelta}${RESET}`); put(out, 33, 23, `${theme}RESULT: ${preview.finalArgument} ARGUMENT / ${preview.finalContempt} CONTEMPT${RESET}`); if (cols > 88) put(out, 33, 24, `${DIM}${theme}${preview.trace[preview.trace.length - 1] ?? ''}${RESET}`); }
function renderCaseResult(out: string[], cols: number, theme: string): void { const state = frameState; const preview = state?.pendingPreview; center(out, cols, 8, preview?.outcome === 'win' ? '✓ VERDICT ACCEPTED' : '× CASE LOST', preview?.outcome === 'win' ? `${GREEN}${BOLD}` : `${RED}${BOLD}`); center(out, cols, 11, state?.notice ?? '', `${YELLOW}${BOLD}`); center(out, cols, 15, `ARGUMENT ${state?.activeCase?.argument ?? 0}   CONTEMPT ${state?.activeCase?.contempt ?? 0}   STANDING ${state?.standing ?? 0}`, theme); footer(out, cols, 'ENTER CONTINUE   R RETRY RUN   Q QUIT', theme); }
function renderPrecedents(out: string[], cols: number, theme: string, selection: number): void { const state = frameState; box(out, 8, 5, cols - 16, 19, theme); put(out, 11, 6, `${theme}${BOLD}OPINION DRAFT${RESET}`); (state?.rewardOptions ?? []).forEach((id, i) => { const item = precedentById(id); if (!item) return; const color = i === selection ? `${YELLOW}${BOLD}` : theme; put(out, 12, 9 + i * 4, `${color}${i + 1}. ¶ ${item.name}${RESET}`); put(out, 17, 10 + i * 4, `${DIM}${theme}${item.text}${RESET}`); }); put(out, 12, 22, `${theme}ACTIVE CHAIN: ${(state?.precedentIds ?? []).map(id => precedentById(id)?.name).join(' > ') || 'EMPTY'}${RESET}`); footer(out, cols, '1-3 ADOPT / REPLACE OLDEST   D DISTINGUISH FOR +2 FEES', theme); }
function renderChambers(out: string[], cols: number, theme: string, selection: number): void { const state = frameState; box(out, 10, 5, cols - 20, 19, theme); put(out, 13, 6, `${theme}${BOLD}CHAMBERS // ONE SERVICE${RESET}`); const services = ['1 HEAL: 3 FEES -> +2 STANDING', '2 POLISH: 2 FEES -> RAISE FIRST ELIGIBLE FACE', '3 EXPUNGE: 4 FEES -> REMOVE FIRST GAFFE', '4 SUBPOENA: 2 FEES -> ADD FIRST NEW EXHIBIT']; services.forEach((text, i) => put(out, 15, 9 + i * 2, `${i === selection ? `${YELLOW}${BOLD}` : theme}${text}${RESET}`)); put(out, 15, 19, `${DIM}${theme}PRECEDENT ORDER: ${state?.precedentIds.join(' > ') || 'EMPTY'}${RESET}`); footer(out, cols, '1-4 BUY SERVICE   ENTER LEAVE CHAMBERS   ARROWS MOVE', theme); }
function renderCircuit(out: string[], cols: number, theme: string): void { center(out, cols, 9, '§ CIRCUIT REPORT', `${CYAN}${BOLD}`); center(out, cols, 12, 'The docket is closed. The next bench has been selected.', theme); center(out, cols, 15, 'ENTER: OPEN NEXT DOCKET', `${YELLOW}${BOLD}`); footer(out, cols, 'ENTER CONTINUE   ESC PAUSE', theme); }
function renderEnding(out: string[], state: GameState, cols: number, theme: string): void { const won = state.phase === 'ending'; center(out, cols, 8, won ? '✓ THE TRIBUNAL ENDURES' : '× STANDING EXHAUSTED', won ? `${GREEN}${BOLD}` : `${RED}${BOLD}`); center(out, cols, 11, state.notice, `${YELLOW}${BOLD}`); center(out, cols, 14, `CASES WON ${state.history.filter(item => item.won).length}/9   PRECEDENTS ${state.precedentIds.length}/4`, theme); footer(out, cols, 'R RESTART   N NEXT GAME   Q QUIT', theme); }
function renderHelp(out: string[], cols: number, rows: number, theme: string): void { const x = Math.max(4, Math.floor((cols - 58) / 2)); const y = Math.max(5, Math.floor((rows - 14) / 2)); box(out, x - 2, y - 2, 62, 16, MAGENTA); put(out, x, y, `${MAGENTA}${BOLD}? TRIBUNAL HELP${RESET}`); ['F/W/L/R/O are evidence faces; X is a Gaffe.', 'Assignments are reversible until Commit.', 'Rerolling a die that finishes X adds its reroll count.', 'O blocks Pressure. Clarify uses any normal face.', 'All Commit totals are shown before you confirm.', 'ESC pauses. Q quits from safe screens.'].forEach((line, i) => put(out, x, y + 2 + i * 2, `${theme}${line}${RESET}`)); }
