import { ADVOCATES, caseById, evidenceById, judgeById, precedentById } from './content';
import { previewHearing } from './evaluator';
import type { FaceSymbol, GameState, Rank } from './types';
import { clipToWidth, padToWidth, wrapText } from '../../ui/terminal';
import { getCurrentThemePalette, type TerminalThemePalette } from '../utils';

const RESET = '\x1b[0m';
const BOLD = '\x1b[1m';
const MIN_COLS = 80;
const MIN_ROWS = 24;
const FACE: Record<FaceSymbol, string> = { fact: 'F', witness: 'W', law: 'L', rhetoric: 'R', objection: 'O', gaffe: 'X' };

export interface DiceRenderModel { selection?: number; helpOpen?: boolean; paused?: boolean; }
const row = (text: string, width: number, style = ''): string => `${style}${padToWidth(clipToWidth(text, width, ''), width)}${RESET}`;
const rule = (title: string, width: number, palette: TerminalThemePalette): string => `${palette.line}${BOLD}-- ${title} ${'-'.repeat(Math.max(0, width - title.length - 4))}${RESET}`;
const faceCode = (symbol: FaceSymbol | undefined, rank: Rank | 0 | undefined): string => symbol ? `[${FACE[symbol]}${rank || ' '}]` : '[--]';

function resize(cols: number, rows: number, palette: TerminalThemePalette): string { return ['\x1b[2J\x1b[H', row('g/ DICE TRIBUNAL', cols, `${palette.focus}${BOLD}`), '', row('COURT NEEDS MORE ROOM', cols, `${palette.warning}${BOLD}`), row(`NEED ${MIN_COLS}x${MIN_ROWS}  HAVE ${cols}x${rows}`, cols, palette.muted), '', row('Resize the terminal to keep the case file readable.', cols, palette.ink)].join('\n'); }
function start(cols: number, palette: TerminalThemePalette): string { return ['\x1b[2J\x1b[H', '', row('g/ DICE TRIBUNAL', cols, `${palette.focus}${BOLD}`), row('ROLL THE EVIDENCE. RISK THE REROLL. REWRITE PRECEDENT.', cols, palette.ink), '', row('A courtroom filing game where every die has a legal job.', cols, palette.muted), '', row('[P] CAMPAIGN    [T] TUTORIAL    [Q] QUIT', cols, palette.focus), '', row('The clerk will show the arithmetic before you file.', cols, palette.muted)].join('\n'); }
function header(state: GameState, width: number, palette: TerminalThemePalette): string[] { return [row(`g/ DICE TRIBUNAL   CIRCUIT ${state.circuit}  CASE ${Math.min(9, state.caseNumber || state.history.length + 1)}/9`, width, `${palette.focus}${BOLD}`), row(`STANDING ${state.standing}/${state.maxStanding}  FEES ${state.fees}  ${state.notice}`, width, palette.muted), '']; }
function help(width: number, palette: TerminalThemePalette): string { return ['\x1b[2J\x1b[H', row('g/ DICE TRIBUNAL / CLERK NOTES', width, `${palette.focus}${BOLD}`), '', row('Numbers select a visible item. Arrows move the selection.', width, palette.ink), row('Enter rolls first, then previews, then confirms the hearing.', width, palette.ink), row('R marks the selected die for reroll; Enter does not reroll it.', width, palette.ink), row('F assigns the selected die to its first matching exhibit slot.', width, palette.ink), row('C assigns Clarify. O assigns Object. U removes an assignment.', width, palette.ink), row('X suggests assignments. Backspace cancels an open preview.', width, palette.ink), row('? or H closes these notes. Escape opens the shared pause menu.', width, palette.muted)].join('\n'); }

function advocates(width: number, palette: TerminalThemePalette, selection: number): string[] { const out = [rule('CHOOSE ADVOCATE', width, palette)]; ADVOCATES.forEach((item, index) => { const selected = index === selection; out.push(row(`${selected ? '>' : ' '} ${index + 1}. ${item.name} // ${item.title}`, width, selected ? palette.focus : palette.ink)); out.push(row(`    ${item.passive}`, width, palette.muted)); }); out.push('', row('Arrows / 1-4 select  Enter confirms', width, palette.muted)); return out; }
function docket(state: GameState, width: number, palette: TerminalThemePalette, selection: number): string[] { const out = [rule('DOCKET / DISCLOSED BURDEN', width, palette)]; state.docket.forEach((choice, index) => { const item = caseById(choice.caseId); const judge = judgeById(choice.judgeId); const selected = index === selection; out.push(row(`${selected ? '>' : ' '} ${index + 1}. ${item?.title ?? choice.caseId}`, width, selected ? palette.focus : palette.ink)); out.push(row(`    ${item?.client} v ${item?.opponent}  BURDEN ${choice.burden}  PRESSURE ${choice.pressure.join('/')}`, width, palette.muted)); out.push(row(`    BENCH ${judge?.name ?? choice.judgeId}  ${item?.premise ?? ''}`, width, palette.ink)); }); out.push('', row('Arrows / 1-2 select  Enter files the docket', width, palette.muted)); return out; }
function briefing(state: GameState, width: number, palette: TerminalThemePalette): string[] { const item = state.activeCase ? caseById(state.activeCase.definitionId) : undefined; const judge = state.activeCase ? judgeById(state.activeCase.judgeId) : undefined; return [rule('CASE FILE / BENCH INTERPRETATION', width, palette), row(`${item?.title ?? 'CASE'}  ${item?.client ?? ''} v ${item?.opponent ?? ''}`, width, palette.focus), ...wrapText(item?.premise ?? '', width - 4).slice(0, 2).map(text => row(text, width, palette.ink)), '', row(`BENCH ${judge?.name ?? ''}`, width, palette.warning), row(`1 DEFAULT  ${judge?.defaultInterpretation.title ?? ''}`, width, palette.ink), row(`2 MOTION   ${judge?.alternateInterpretation.title ?? ''}  FEE ${judge?.alternateInterpretation.fee ?? 0}`, width, palette.ink), '', row('1/2 choose interpretation  Enter accepts default', width, palette.muted)]; }
function evidenceSelect(state: GameState, width: number, palette: TerminalThemePalette, selection: number): string[] { const out = [rule('CASE FILE / FOUR EXHIBITS', width, palette), row(`SELECTED ${state.activeCase?.selectedEvidenceIds.length ?? 0}/4`, width, palette.focus)]; state.evidencePortfolio.forEach((id, index) => { const item = evidenceById(id); if (!item) return; const selected = state.activeCase?.selectedEvidenceIds.includes(id); out.push(row(`${index === selection ? '>' : ' '} ${selected ? '[+]' : '[ ]'} ${index + 1}. ${item.name}  ${item.slots.map(slot => `${FACE[slot.symbol]}${slot.minRank}`).join(' ')}`, width, index === selection ? palette.focus : selected ? palette.good : palette.ink)); }); out.push('', row('Numbers toggle exhibits  Enter confirms exactly four', width, palette.muted)); return out; }
function dieRows(state: GameState, width: number, palette: TerminalThemePalette, selection: number): string[] { const out = [rule('DICE RACK / ASSIGNMENT', width, palette)]; state.dice.forEach((die, index) => { const rolled = state.activeCase?.hearing.rolled.find(item => item.dieId === die.id); const face = rolled ? die.faces[rolled.faceIndex] : undefined; const assignment = state.activeCase?.hearing.assignments.find(item => item.dieId === die.id); const destination = assignment ? assignment.target.kind === 'evidence' ? `${assignment.target.evidenceId}:${assignment.target.slotIndex + 1}` : assignment.target.kind.toUpperCase() : 'unassigned'; const reroll = rolled?.marked ? '[R]' : rolled?.rerollCount ? `x${rolled.rerollCount}` : '[ ]'; out.push(row(`${index === selection ? '>' : ' '} [${index + 1}] ${die.name.slice(0, 10).padEnd(10)} ${faceCode(face?.symbol, face?.rank)} ${reroll} -> ${destination}`, width, index === selection ? palette.focus : face?.symbol === 'gaffe' ? palette.danger : palette.ink)); }); out.push(row(`REROLLS ${state.activeCase?.hearing.rerollsRemaining ?? 0}  F file  C clarify  O object  U unassign`, width, palette.muted)); return out; }
function hearing(state: GameState, width: number, palette: TerminalThemePalette, selection: number): string[] { const active = state.activeCase!; const out = [rule(`HEARING ${active.hearing.index + 1}/${active.pressure.length}`, width, palette), row(`ARGUMENT ${active.argument}/${active.burden}  CONTEMPT ${active.contempt}/${active.contemptLimit}  PRESSURE ${active.pressure[active.hearing.index] ?? 0}`, width, palette.focus), ...dieRows(state, width, palette, selection), '', rule('CASE FILE SLOTS', width, palette)]; active.selectedEvidenceIds.forEach(id => { const item = evidenceById(id); if (!item) return; const slots = item.slots.map((_, index) => active.hearing.assignments.find(a => a.target.kind === 'evidence' && a.target.evidenceId === id && a.target.slotIndex === index) ? '[+]' : '[ ]').join(' '); out.push(row(`${slots} ${item.name}`, width, active.admittedEvidenceIds.includes(id) ? palette.muted : palette.ink)); }); out.push('', rule('CLERK TRACE', width, palette)); const preview = state.pendingPreview ?? (state.activeCase?.hearing.rolled.length ? previewHearing(state) : null); if (preview && !preview.legal) out.push(row(`[!] ${preview.error ?? 'Filing incomplete.'}`, width, palette.warning)); else if (preview) out.push(row(`PREVIEW  ARG ${preview.finalArgument}  CONTEMPT ${preview.finalContempt}  ${preview.outcome.toUpperCase()}`, width, palette.good), ...preview.trace.slice(-3).map(text => row(text, width, palette.muted))); else out.push(row('Enter rolls the record. Then assign dice and preview.', width, palette.muted)); out.push('', row(state.pendingPreview ? 'ENTER FILES  BACKSPACE CANCELS' : 'Enter roll/preview  R reroll mark  X suggest  Esc pause  H help', width, palette.muted)); return out; }
function results(state: GameState, width: number, palette: TerminalThemePalette): string[] { const preview = state.pendingPreview; return [rule('CLERK REPORT', width, palette), row(state.notice, width, state.phase === 'caseResult' ? palette.good : palette.warning), row(`ARGUMENT ${state.activeCase?.argument ?? 0}  CONTEMPT ${state.activeCase?.contempt ?? 0}  STANDING ${state.standing}`, width, palette.ink), ...(preview?.trace ?? []).slice(-5).map(text => row(text, width, palette.muted)), '', row('Enter continues  R retries  Q quits', width, palette.muted)]; }
function longChoice(state: GameState, width: number, palette: TerminalThemePalette, titleText: string): string[] { const out = [rule(titleText, width, palette)]; (state.rewardOptions.length ? state.rewardOptions : state.precedentIds).slice(0, 4).forEach((id, index) => out.push(row(`${index + 1}. ${precedentById(id)?.name ?? id}`, width, palette.ink))); out.push('', row(state.notice, width, palette.muted), row('Numbers choose  Enter confirms the screen action', width, palette.muted)); return out; }

export function renderFrame(state: GameState, cols: number, rows: number, palette: TerminalThemePalette = getCurrentThemePalette(), model: DiceRenderModel = {}): string {
  if (cols < MIN_COLS || rows < MIN_ROWS) return resize(cols, rows, palette);
  const width = Math.max(74, cols - 6);
  if (model.helpOpen) return help(width, palette);
  if (state.phase === 'start') return start(cols, palette);
  const out = ['\x1b[2J\x1b[H', ...header(state, width, palette)];
  if (state.phase === 'advocateSelect') out.push(...advocates(width, palette, model.selection ?? 0));
  else if (state.phase === 'docket') out.push(...docket(state, width, palette, model.selection ?? 0));
  else if (state.phase === 'briefing') out.push(...briefing(state, width, palette));
  else if (state.phase === 'evidenceSelect') out.push(...evidenceSelect(state, width, palette, model.selection ?? 0));
  else if (state.phase === 'hearing' || state.phase === 'hearingResult') out.push(...hearing(state, width, palette, model.selection ?? 0));
  else if (state.phase === 'caseResult' || state.phase === 'gameOver') out.push(...results(state, width, palette));
  else if (state.phase === 'precedentDraft') out.push(...longChoice(state, width, palette, 'OPINION MARGIN / ADOPT OR DISTINGUISH'));
  else if (state.phase === 'chambers') out.push(...longChoice(state, width, palette, 'CHAMBERS / ONE SERVICE'));
  else if (state.phase === 'circuitReport') out.push(...results(state, width, palette));
  else out.push(...results(state, width, palette));
  while (out.length < rows) out.push('');
  return out.slice(0, rows).join('\n');
}
