import type { Candidate, CallerDefinition, ClaimSlot, EffectBundle, EvidenceItem, TrackDefinition } from './types';

const e = (effects: EffectBundle = {}): EffectBundle => effects;
const response = (label: string, line: string, effects: EffectBundle, risk?: string) => ({ label, line, effects, risk });
const caller = (id: string, alias: string, district: string, faction: CallerDefinition['faction'], topic: string, urgency: CallerDefinition['urgency'], source: CallerDefinition['source'], intro: string, left: ReturnType<typeof response>, right: ReturnType<typeof response>): CallerDefinition => ({ id, alias, district, faction, topic, urgency, source, intro, responses: [left, right] });

export const CANDIDATES: Candidate[] = [
  { id: 'halcyon', slot: 'operator', label: 'HALCYON CIVIC SYSTEMS' },
  { id: 'emergency-office', slot: 'operator', label: 'EMERGENCY OFFICE ALONE' },
  { id: 'bellwether-voice', slot: 'operator', label: 'BELLWETHER VOICE' },
  { id: 'transit-union', slot: 'operator', label: 'TRANSIT UNION' },
  { id: 'forged-alert', slot: 'method', label: 'FORGED CHLORINE ALERT' },
  { id: 'grid-overload', slot: 'method', label: 'GRID OVERLOAD' },
  { id: 'poisoned-water', slot: 'method', label: 'POISONED RESERVOIR' },
  { id: 'tone', slot: 'method', label: 'CALMING TONE TEST' },
  { id: 'old-crown', slot: 'origin', label: 'OLD CROWN EXCHANGE' },
  { id: 'reservoir', slot: 'origin', label: 'NORTH RESERVOIR' },
  { id: 'metro', slot: 'origin', label: 'METRO CONTROL' },
  { id: 'tower', slot: 'origin', label: 'HARBOR TOWER' },
  { id: 'harbor-clearance', slot: 'objective', label: 'EMPTY HARBOR WARD' },
  { id: 'transfer', slot: 'objective', label: 'COVER A TRANSFER' },
  { id: 'markets', slot: 'objective', label: 'MOVE UTILITY MARKETS' },
  { id: 'drill', slot: 'objective', label: 'HARMLESS DRILL' },
];

export const EVIDENCE: EvidenceItem[] = [
  { id: 'clock-bus', title: '03:17 route display', summary: 'Four buses showed the same activation time before any alert was issued.', slot: 'method', candidateId: 'forged-alert', sourceGroup: 'night-shift-transit', reliability: 2, status: 'unverified', acquiredRound: 0 },
  { id: 'old-crown-vans', title: 'Halcyon vans at Old Crown', summary: 'A rooftop photograph places Halcyon maintenance vans below the abandoned exchange.', slot: 'operator', candidateId: 'halcyon', sourceGroup: 'rooftops-photo', reliability: 2, status: 'unverified', acquiredRound: 0 },
  { id: 'leaflet', title: 'Preprinted evacuation leaflet', summary: 'Harbor Ward leaflets name a chlorine wind before sensors report one.', slot: 'objective', candidateId: 'harbor-clearance', sourceGroup: 'harbor-tenants', reliability: 2, status: 'unverified', acquiredRound: 0 },
  { id: 'hospital-clear', title: 'No chlorine protocol', summary: 'The hospital night desk has no scheduled chlorine response at 03:17.', slot: 'method', candidateId: 'forged-alert', sourceGroup: 'hospital-desk', reliability: 2, status: 'unverified', acquiredRound: 0 },
  { id: 'bridge-workorder', title: 'Illegal alert bridge', summary: 'A meter technician found a municipal alert bridge with a Halcyon serial prefix.', slot: 'operator', candidateId: 'halcyon', sourceGroup: 'meter-tech', reliability: 3, status: 'unverified', acquiredRound: 0 },
  { id: 'routine-drill', title: 'Routine drill statement', summary: 'The city statement calls the event a drill but cannot name its incident number.', slot: 'method', candidateId: 'drill', sourceGroup: 'city-statement', reliability: 1, status: 'unverified', acquiredRound: 0 },
  { id: 'injunction', title: 'Unserved clearance injunction', summary: 'A court clerk has a signed injunction that would stop dawn clearance in Harbor Ward.', slot: 'objective', candidateId: 'harbor-clearance', sourceGroup: 'court-clerk', reliability: 3, status: 'unverified', acquiredRound: 0 },
  { id: 'union-alibi', title: 'Transit union alibi', summary: 'The union has no access to the municipal relay contract or Old Crown keys.', slot: 'operator', candidateId: 'transit-union', sourceGroup: 'union-ledger', reliability: 2, status: 'unverified', acquiredRound: 0 },
  { id: 'handshake', title: 'Halcyon carrier handshake', summary: 'A former audio engineer recognizes the injection header used by Halcyon test rigs.', slot: 'operator', candidateId: 'halcyon', sourceGroup: 'halcyon-engineer', reliability: 3, status: 'unverified', acquiredRound: 0 },
  { id: 'sensor-log', title: 'Clean sensor log', summary: 'Independent sanitation logs show no chlorine release along the alert route.', slot: 'method', candidateId: 'forged-alert', sourceGroup: 'sanitation-log', reliability: 3, status: 'unverified', acquiredRound: 0 },
  { id: 'leased-line', title: 'Leased line to Old Crown', summary: 'The night dispatcher follows an unlisted municipal line into Old Crown Exchange.', slot: 'origin', candidateId: 'old-crown', sourceGroup: 'train-dispatch', reliability: 2, status: 'unverified', acquiredRound: 0 },
  { id: 'carrier-recording', title: 'Matching carrier recording', summary: 'A Deep Dial recording matches the timing and phase of the Old Crown line.', slot: 'origin', candidateId: 'old-crown', sourceGroup: 'deep-dial-recording', reliability: 3, status: 'unverified', acquiredRound: 0 },
  { id: 'clearance-crews', title: 'Private clearance crews', summary: 'A guard saw private security staging beside Harbor Ward before the alert window.', slot: 'objective', candidateId: 'harbor-clearance', sourceGroup: 'security-guard', reliability: 2, status: 'unverified', acquiredRound: 0 },
  { id: 'safe-route', title: 'Harbor mutual-aid route', summary: 'Blockwatch has a safe route that only makes sense if the ward is meant to empty.', slot: 'objective', candidateId: 'harbor-clearance', sourceGroup: 'blockwatch-route', reliability: 2, status: 'unverified', acquiredRound: 0 },
  { id: 'stolen-code', title: 'Stolen authorization code', summary: 'An emergency operator reports a Halcyon contractor requesting the alert code early.', slot: 'method', candidateId: 'forged-alert', sourceGroup: 'emergency-operator', reliability: 2, status: 'unverified', acquiredRound: 0 },
  { id: 'archive-contract', title: 'Archive contract match', summary: 'An old contract ties the leased line, Halcyon serial prefix, and Old Crown room together.', slot: 'operator', candidateId: 'halcyon', sourceGroup: 'city-archive', reliability: 3, status: 'unverified', acquiredRound: 0 },
  { id: 'dawn-order', title: 'Dawn clearance order', summary: 'The final source authenticates a 03:17 alert followed by a private-security clearance.', slot: 'objective', candidateId: 'harbor-clearance', sourceGroup: 'halcyon-whistleblower', reliability: 3, status: 'unverified', acquiredRound: 0 },
];

export const CALLERS: Record<string, CallerDefinition> = {
  bus: caller('bus', 'LINE SEVEN', 'South Loop', 'nightShift', 'Every route display blinked 03:17.', 'TIME-SENSITIVE', 'FIRSTHAND', 'The driver sounds tired, precise, and very awake.', response('READ THE WORK ORDER', '“It says emergency bridge test. No city seal.”', e({ credibility: 2, trust: { nightShift: 5 }, evidence: ['clock-bus'] })), response('KEEP THE ROUTE MOVING', '“Do not name your depot. Get everyone home.”', e({ signal: 2, trace: -2, trust: { nightShift: 7, blockwatch: 2 }, callback: true }), 'Caller safety protected')),
  rooftop: caller('rooftop', 'SUNDIAL', 'West Roofs', 'rooftops', 'Halcyon vans are under Old Crown Exchange.', 'ROUTINE', 'HAS RECORDING', 'A camera shutter clicks behind the voice.', response('ASK FOR A STILL', '“Timestamp, van logo, and the room light. Send it.”', e({ trace: 2, trust: { rooftops: 5 }, evidence: ['old-crown-vans'] })), response('PUT IT ON AIR', '“Bellwether, look at Old Crown. Right now.”', e({ credibility: -4, signal: 4, trust: { rooftops: 8, blockwatch: -2 }, evidence: ['old-crown-vans'] }), 'Source location exposed')),
  tenant: caller('tenant', 'MINT TEA', 'Harbor Ward', 'blockwatch', 'Evacuation leaflets arrived before an alert.', 'IN DANGER', 'HAS RECORDING', 'Paper rustles. A child asks whether the sirens are real.', response('READ THE DATE, NOT THE ADDRESS', '“Tell us when it was printed. Keep your doorway private.”', e({ credibility: 3, trust: { blockwatch: 8 }, evidence: ['leaflet'], callback: true })), response('NAME THE BUILDING', '“Everyone on Juniper Court, listen now.”', e({ signal: 6, trace: 5, credibility: 1, trust: { blockwatch: -6, rooftops: 3 }, evidence: ['leaflet'] }), 'Source location exposed')),
  hospital: caller('hospital', 'NIGHT DESK', 'Mercy Hospital', 'nightShift', 'No chlorine response is scheduled.', 'TIME-SENSITIVE', 'FIRSTHAND', 'A pager chirps twice, then stops.', response('CHECK THE PROTOCOL', '“If the sensors are clean, the alert is a lie.”', e({ credibility: 2, trust: { nightShift: 5 }, evidence: ['hospital-clear'] })), response('KEEP THE WARD CALM', '“Do not send a crowd toward the hospital.”', e({ trace: -3, trust: { nightShift: 7, blockwatch: 3 }, evidence: ['hospital-clear'], callback: true }))),
  meter: caller('meter', 'COPPER', 'East Utility', 'deepDial', 'An illegal alert bridge bears a Halcyon prefix.', 'TIME-SENSITIVE', 'FIRSTHAND', 'Tools clink in the background. The caller keeps checking a door.', response('READ THE SERIAL', '“Give us the prefix and stop touching the bridge.”', e({ credibility: 2, trust: { deepDial: 7 }, evidence: ['bridge-workorder'] })), response('ASK WHO PAID', '“Name the contractor, then move.”', e({ trace: 3, trust: { deepDial: 5, blockwatch: 2 }, evidence: ['bridge-workorder'], callback: true }))),
  spokesperson: caller('spokesperson', 'CITY DESK', 'Civic Center', 'nightShift', 'The city calls tonight a harmless drill.', 'ROUTINE', 'OFFICIAL', 'The statement is too smooth for an unscheduled call.', response('ASK FOR AN INCIDENT NUMBER', '“A drill has a number. Put it on the record.”', e({ credibility: 5, trust: { nightShift: 4, deepDial: 3 }, evidence: ['routine-drill'] })), response('ACCEPT THE DRILL', '“Everyone can stand down. It is probably nothing.”', e({ credibility: -6, trust: { nightShift: 4, blockwatch: -3 }, evidence: ['routine-drill'] }), 'Official framing repeated')),
  clerk: caller('clerk', 'PAPER TRAIL', 'Crown Court', 'blockwatch', 'A dawn clearance injunction is still unserved.', 'TIME-SENSITIVE', 'HAS RECORDING', 'A scanner hums while a document is turned face-down.', response('VERIFY THE DOCKET', '“Read the seal. Do not read the tenant names.”', e({ credibility: 3, trust: { blockwatch: 7 }, evidence: ['injunction'] })), response('READ EVERY NAME', '“Harbor Ward, this is your warning.”', e({ credibility: -3, trace: 4, trust: { blockwatch: -4, rooftops: 4 }, evidence: ['injunction'] }), 'Private names exposed')),
  rival: caller('rival', 'BELLWETHER VOICE', 'Unknown', 'rooftops', 'The transit union is staging a blackout.', 'ROUTINE', 'HEARD SECONDHAND', 'Their claim arrives with no timestamp and a slogan.', response('ASK FOR A SOURCE', '“No names, no accusation. What did you actually see?”', e({ credibility: 4, trust: { rooftops: 4, deepDial: 3 } })), response('REPEAT THE CHARGE', '“The union wants the city dark.”', e({ credibility: -9, trace: 4, trust: { rooftops: 7, nightShift: -8 }, evidence: ['union-alibi'] }), 'Unsupported accusation')),
  engineer: caller('engineer', 'SOLDER', 'Northside Flats', 'deepDial', 'The injection header belongs to Halcyon test rigs.', 'IN DANGER', 'FIRSTHAND', 'The voice knows the difference between a relay and a recording.', response('COMPARE THE HANDSHAKE', '“Give us three header beats. Then leave the room.”', e({ credibility: 4, trust: { deepDial: 8 }, evidence: ['handshake'], callback: true })), response('ASK FOR A CONFESSION', '“Say Halcyon on air. Make them answer.”', e({ trace: 6, credibility: 1, trust: { deepDial: 5, rooftops: 3 }, evidence: ['handshake'] }), 'Source exposed')),
  sanitation: caller('sanitation', 'BLUE GLOVES', 'North Reservoir', 'nightShift', 'The chlorine sensors are clean.', 'TIME-SENSITIVE', 'HAS RECORDING', 'A meter ticks at a steady, reassuring pace.', response('LOG THE READING', '“Timestamp the clean sample. Let the false alarm contradict itself.”', e({ credibility: 3, trust: { nightShift: 6, deepDial: 4 }, evidence: ['sensor-log'] })), response('CALL IT A COVER-UP', '“The clean reading proves the reservoir is hiding something.”', e({ credibility: -7, trace: 3, trust: { nightShift: -5, rooftops: 4 }, evidence: ['sensor-log'] }), 'Contradiction ignored')),
  dispatcher: caller('dispatcher', 'NIGHT TRAIN', 'South Line', 'nightShift', 'An unlisted leased line runs to Old Crown.', 'TIME-SENSITIVE', 'FIRSTHAND', 'The dispatcher has drawn the route on a paper timetable.', response('FOLLOW THE LEASE', '“Read the endpoint, not the passengers.”', e({ credibility: 2, trust: { nightShift: 6 }, evidence: ['leased-line'] })), response('BROADCAST THE ROUTE', '“Everyone, converge on Old Crown.”', e({ signal: 5, trace: 6, trust: { rooftops: 5, blockwatch: -3 }, evidence: ['leased-line'] }), 'Crowd directed to a live site')),
  dial: caller('dial', 'SUNDIAL TWO', 'West Roofs', 'deepDial', 'A recording matches the Old Crown carrier phase.', 'ROUTINE', 'HAS RECORDING', 'A careful listener has labeled every tape by minute.', response('PLAY THE COMPARISON', '“One carrier, two instruments. Let us make it boring.”', e({ credibility: 4, trust: { deepDial: 7 }, evidence: ['carrier-recording'] })), response('CHASE THE GHOST', '“If it moves, follow it. Keep recording.”', e({ signal: 4, trace: 3, trust: { deepDial: 5, rooftops: 2 }, evidence: ['carrier-recording'], callback: true }))),
  guard: caller('guard', 'NIGHT WATCH', 'Harbor Edge', 'blockwatch', 'Private clearance crews are staged before dawn.', 'IN DANGER', 'FIRSTHAND', 'The guard speaks from a locked booth and keeps the details plain.', response('ASK FOR THE BADGE', '“A uniform is not proof. What contract is on the van?”', e({ credibility: 3, trust: { blockwatch: 7 }, evidence: ['clearance-crews'] })), response('NAME THE CREW', '“Harbor Ward, the private security is coming.”', e({ trace: 5, signal: 4, trust: { blockwatch: -2, rooftops: 5 }, evidence: ['clearance-crews'] }), 'Witness location exposed')),
  organizer: caller('organizer', 'MOSAIC', 'Harbor Ward', 'blockwatch', 'Mutual aid can keep neighbors safe if the show stays calm.', 'IN DANGER', 'FIRSTHAND', 'They ask for a route, not a headline.', response('MAP THE SAFE ROOF', '“Give us a route that does not name a doorway.”', e({ credibility: 3, trust: { blockwatch: 9, nightShift: 3 }, evidence: ['safe-route'], callback: true })), response('CALL FOR A CROWD', '“Everyone to Harbor Ward now.”', e({ trace: 7, signal: 5, trust: { blockwatch: -5, rooftops: 7 }, evidence: ['safe-route'] }), 'Panic risk')),
  operator: caller('operator', 'EMERGENCY DESK', 'Civic Center', 'nightShift', 'A Halcyon contractor requested the alert code early.', 'IN DANGER', 'FIRSTHAND', 'The operator whispers as though the console can hear.', response('VERIFY THE REQUEST', '“Read the time and requestor. Keep your name out of it.”', e({ credibility: 4, trust: { nightShift: 8 }, evidence: ['stolen-code'], callback: true })), response('PUT THEM ON SPEAKER', '“Tell the city who is holding the code.”', e({ trace: 6, credibility: 1, trust: { nightShift: -4, rooftops: 4 }, evidence: ['stolen-code'] }), 'Caller exposed')),
  plant: caller('plant', 'ANGRY CITIZEN', 'Unknown', 'rooftops', 'Violence will stop the alert before it starts.', 'IN DANGER', 'UNKNOWN', 'The caller knows the slogan but not the street names.', response('REFUSE THE BAIT', '“No violence. Give us one checkable fact or leave.”', e({ credibility: 5, trust: { rooftops: 3, blockwatch: 4 } })), response('AMPLIFY THE THREAT', '“If they want a fight, give them one.”', e({ credibility: -12, trace: 8, trust: { rooftops: 6, blockwatch: -8 }, flags: ['plant-amplified'] }), 'Plant framing amplified')),
  whistleblower: caller('whistleblower', 'GLASSHOUSE', 'Halcyon Annex', 'deepDial', 'A whistleblower can authenticate the order at 03:17.', 'IN DANGER', 'HAS RECORDING', 'A contract page is held beside a carrier recording.', response('AUTHENTICATE, THEN CUT', '“Give us the phrase. We will not keep your line open.”', e({ credibility: 5, trust: { deepDial: 8, blockwatch: 3 }, evidence: ['dawn-order'], callback: true })), response('STAY ON AIR', '“Say everything. Let the city hear the whole machine.”', e({ credibility: 3, trace: 9, signal: 4, trust: { rooftops: 5, deepDial: 4 }, evidence: ['dawn-order'] }), 'Source exposed')),
  archive: caller('archive', 'CITY ARCHIVE', 'Old Crown', 'deepDial', 'A contract links Halcyon, Old Crown, and the leased line.', 'ROUTINE', 'HAS RECORDING', 'The archivist sounds relieved that someone finally asked.', response('SCAN THE THREE LINKS', '“Contract, room, line. Keep the names on paper.”', e({ credibility: 4, trust: { deepDial: 7 }, evidence: ['archive-contract'] })), response('READ THE COMPANY LIST', '“Every Halcyon client, right now.”', e({ signal: 4, trace: 5, trust: { deepDial: 2, blockwatch: -2 }, evidence: ['archive-contract'] }), 'Archive source exposed')),
};

export const ROUND_OFFERS: Array<[string, string]> = [
  ['bus', 'rooftop'], ['tenant', 'hospital'], ['meter', 'spokesperson'], ['clerk', 'rival'],
  ['engineer', 'sanitation'], ['dispatcher', 'dial'], ['guard', 'organizer'], ['operator', 'plant'], ['whistleblower', 'archive'],
];

export const TRACKS: Record<string, TrackDefinition> = {
  bus: { id: 'bus', title: 'Night Bus Home', artist: 'Marrow FM', tags: ['warm', 'night'], workUnits: 2, masking: 1, effects: e({ trust: { nightShift: 6, blockwatch: 2 } }), cooldown: 2 },
  hall: { id: 'hall', title: 'Keep the Hall Light On', artist: 'June Harbor', tags: ['warm', 'care'], workUnits: 2, masking: 1, effects: e({ credibility: 2, trust: { blockwatch: 6 } }), cooldown: 2 },
  antenna: { id: 'antenna', title: 'Teeth of the Antenna', artist: 'Static Saints', tags: ['loud', 'rooftop'], workUnits: 1, masking: 3, effects: e({ trace: 2, trust: { rooftops: 7 } }), cooldown: 3 },
  gods: { id: 'gods', title: 'No Gods on the Dial', artist: 'Wires Awake', tags: ['loud', 'rooftop'], workUnits: 2, masking: 2, effects: e({ trust: { rooftops: 5, deepDial: 2 } }), cooldown: 3 },
  carrier: { id: 'carrier', title: 'Carrier Wave Lullaby', artist: 'Iona Kett', tags: ['ambient', 'technical'], workUnits: 3, masking: 2, effects: e({ trust: { deepDial: 6 }, flags: ['carrier-probe'] }), cooldown: 2 },
  numbers: { id: 'numbers', title: 'Numbers Under Rain', artist: 'Pale Index', tags: ['ambient', 'technical'], workUnits: 2, masking: 3, effects: e({ trust: { deepDial: 7, nightShift: -2 } }), cooldown: 3 },
  soup: { id: 'soup', title: 'Soup at Four A.M.', artist: 'Common Room', tags: ['care', 'long'], workUnits: 3, masking: 0, effects: e({ trust: { blockwatch: 4, nightShift: 4 } }), cooldown: 2 },
  union: { id: 'union', title: 'Union of Strangers', artist: 'Coalbirds', tags: ['loud', 'warm'], workUnits: 1, masking: 2, effects: e({ signal: 3, trust: { nightShift: 4, rooftops: 4 } }), cooldown: 3 },
  sideways: { id: 'sideways', title: 'City Sleeps Sideways', artist: 'Velvet Exit', tags: ['dream'], workUnits: 2, masking: 1, effects: e({ trust: { nightShift: 2, rooftops: 2, blockwatch: 2, deepDial: 2 } }), cooldown: 2 },
  weather: { id: 'weather', title: 'The Last Honest Weather', artist: 'Sable Forecast', tags: ['spoken', 'technical'], workUnits: 3, masking: 0, effects: e({ credibility: 3, trust: { deepDial: 5, nightShift: 2 } }), cooldown: 2 },
  glass: { id: 'glass', title: 'Glass Elevator', artist: 'The Understory', tags: ['clean'], workUnits: 1, masking: 2, effects: e({ credibility: 1 }), cooldown: 1 },
  dead: { id: 'dead', title: 'Dead Air Is Still Air', artist: 'Aster Vale', tags: ['damaged', 'technical'], workUnits: 3, masking: 3, effects: e({ signal: -5, trust: { deepDial: 4 } }), cooldown: 3 },
};

export const TRACK_OFFERS: Array<[string, string]> = [
  ['bus', 'antenna'], ['hall', 'carrier'], ['gods', 'soup'], ['numbers', 'sideways'], ['weather', 'union'],
  ['carrier', 'glass'], ['hall', 'dead'], ['antenna', 'weather'], ['soup', 'carrier'],
];

export const BRIEF = [
  'Night Frequency 91.7 is live from a moving van.',
  'At 03:17, Bellwether may receive a false chlorine evacuation alert.',
  'Take the calls. Keep the source chain clean. Make the city hear proof.',
];

export const FACTION_COPY: Record<string, string> = {
  nightShift: 'routes and practical truth', rooftops: 'candor and relay reach', blockwatch: 'safety and source care', deepDial: 'tests and clean records',
};

export function candidatesFor(slot: ClaimSlot): Candidate[] { return CANDIDATES.filter(candidate => candidate.slot === slot); }
